cookie:
  expiry_days: 30
  key: some_signature_key # Must be a string
  name: some_cookie_name
credentials:
  usernames:
    test1:
      email: test1@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Nam
      last_name: SiYul
      logged_in: False # Will be managed automatically
      password: '$2b$12$Akdp5uaa5LFkwrCPuuRRdura7EvFsmDZfC9wQG9A2AgxHODwGHZI6' # Will be hashed automatically
      roles: # Optional
        - admin
        - editor
        - viewer
    test2:
      email: test2@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Kim
      last_name: MinBum
      logged_in: False # Will be managed automatically
      password: '$2b$12$mWWvtWSoGzqiYDYexN8FkOut6N8eBw9b8r4eadwWDqWJ5rZ0s.Wpi' # Will be hashed automatically
      roles: # Optional
        - viewer
